### ISSUE TITLE
IDs löschen

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/virtualqueue#11]
Angestellte IDs, die nicht erschienen sind, sollten gelöscht werden können. Daraus folgend sollte

1. auf dem Gerät der ID angezeigt werden, dass man aus der Schlange entfernt wurde und man sich neu anstellen soll
2. die Warteschlange mit einer neuen ID nachgefüllt werden oder
3. der Counter der standby Queue erhöht werden, um die entfernten Personen in der Menge auszugleichen

**Comment by StevenPaw** [comment]
Maybe will be added in v2.0 but not in this version because of resorting. sry...
