### ISSUE TITLE
Display-Elemente einzeln aktualisieren

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/virtualqueue#3]
Auf der Display-Seite sollen die einzelnen Elemente (Group-IDs, Gäste aus Standby) einzeln aktualisiert werden.
Die gesamte Seite soll nicht mehr aktualisiert werden.

**Comment by StevenPaw** [comment]
Changed in 749948f0b45d621cd143f1f59f559f75bda79b3d
