### ISSUE TITLE
Display-Elemente in Echtzeit aktualisieren

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/virtualqueue#4]
Auf der Display-Seite sollen die einzelnen Elemente (Group-IDs, Gäste aus Standby) in Echtzeit aktualisiert werden.
→ Wenn auf Admin/Display eine Gruppe eingecheckt wird oder Gäste aus der Standby Queue eingecheckt werden, sollen sich die Elemente der Display-Seite sofort aktualisieren

**Comment by zwibblTV** [comment]
Ggf. auch die SQ & IDs auf der Admin/Groups-Seite in Echtzeit aktualisieren?

**Comment by StevenPaw** [comment]
Aufgrund von Transfer-Limitationen leider aktuell nicht möglich. Kommt vielleicht in der v2 der Queue nächstes Jahr
