### ISSUE TITLE
Display: Standby-Gäste nicht kleiner 0

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/virtualqueue#5]
Auf der Display-Seite soll die Anzahl der Gäste, die aus der Standby-Queue eintreten, nicht unter 0 sinken. Also auch wenn die Zahl tatsächlich kleiner 0 ist, dann auf der Seite durch 0 ersetzen.

**Comment by StevenPaw** [comment]
Fixed with 749948f0b45d621cd143f1f59f559f75bda79b3d
