### ISSUE TITLE
Warteschlange beitreten leitet nicht auf Seite weiter

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/virtualqueue#6]
Wenn man (am Handy, Chrome) der Warteschlange beitritt, wird auch "Du hast die Warteschlange betreten!" angezeigt, aber man bleibt auf der Seite und kann der Schlange erneut beitreten. Auf der Admin-Seite wurde aber eine neue ID generiert
Möglicher Fehler: in der Domain steht keine ID/ endet auf "..._?guestid=_"

**Comment by StevenPaw** [comment]
Fixed with dbee402828bc41f0609a4fd492f45caf3944dfad
