### ISSUE TITLE
Feedback Error

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/virtualqueue#7]
Wenn man auf die Feedback-Seite gelangt, erhält man folgenden Fehler-Code:
_Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/speuni/halloweenhaus-schmalenbeck/virtualqueue/layout/header.php:1) in /usr/www/users/speuni/halloweenhaus-schmalenbeck/virtualqueue/main.php on line 109_

**Comment by StevenPaw** [comment]
Fixed in 749948f0b45d621cd143f1f59f559f75bda79b3d
