### ISSUE TITLE
After-Show-Seite & Feedback-Seite zusammen legen?

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/virtualqueue#8]
Sollten wir die "VIELEN DANK FÜR DEINEN BESUCH!"-Seite und die Feedback-Seite zusammen legen, dass man direkt über Ottos Kopf die Show bewerten kann?
Ich könnte mir vorstellen, dass wir dadurch mehr Feedback erhalten.

**Comment by StevenPaw** [comment]
Changed with 3ec026bdbd9e51d7a5d5c9118b21b9dcd2243aa1
